import type {
  McpServerManifest,
  MemoryRecord,
  Permission,
  ProviderConfig,
  SkillManifest,
} from "../domain/types";

export const permissions: Record<string, Permission> = {
  "fs.read": {
    id: "fs.read",
    label: "读取文件",
    level: "read",
    riskLevel: "low",
    description: "读取用户选择的工作区文件和目录。",
  },
  "fs.write": {
    id: "fs.write",
    label: "写入文件",
    level: "write",
    riskLevel: "medium",
    description: "创建或修改工作区内文件。",
  },
  "shell.exec": {
    id: "shell.exec",
    label: "执行命令",
    level: "execute",
    riskLevel: "high",
    description: "在受限执行器或容器沙箱中运行 Shell 命令。",
  },
  "network.http": {
    id: "network.http",
    label: "外部 API",
    level: "external",
    riskLevel: "medium",
    description: "访问用户配置的外部 HTTP 服务。",
  },
  "git.push": {
    id: "git.push",
    label: "推送代码",
    level: "admin",
    riskLevel: "high",
    description: "向远程 Git 仓库推送提交。",
  },
  "secret.read": {
    id: "secret.read",
    label: "读取密钥",
    level: "admin",
    riskLevel: "high",
    description: "从系统 Keychain 读取模型或工具密钥。",
  },
};

export const defaultProviders: ProviderConfig[] = [
  {
    id: "openai-compatible",
    name: "OpenAI Compatible",
    kind: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-5",
    contextWindow: 400_000,
    inputPricePerMTok: 1.25,
    outputPricePerMTok: 10,
    tags: ["balanced", "strong_reasoning", "code_first"],
    enabled: true,
    maskedKey: "未配置",
    status: "untested",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    kind: "anthropic",
    baseUrl: "https://api.anthropic.com",
    model: "claude-sonnet",
    contextWindow: 200_000,
    inputPricePerMTok: 3,
    outputPricePerMTok: 15,
    tags: ["strong_reasoning", "long_context", "code_first"],
    enabled: false,
    maskedKey: "未配置",
    status: "untested",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    kind: "deepseek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-chat",
    contextWindow: 128_000,
    inputPricePerMTok: 0.27,
    outputPricePerMTok: 1.1,
    tags: ["low_cost", "balanced", "code_first"],
    enabled: true,
    maskedKey: "sk-...demo",
    status: "connected",
  },
  {
    id: "qwen",
    name: "Qwen",
    kind: "qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-max",
    contextWindow: 128_000,
    inputPricePerMTok: 1.6,
    outputPricePerMTok: 6.4,
    tags: ["balanced", "long_context"],
    enabled: true,
    maskedKey: "sk-...demo",
    status: "connected",
  },
  {
    id: "kimi",
    name: "Moonshot Kimi",
    kind: "kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "kimi-k2",
    contextWindow: 128_000,
    inputPricePerMTok: 0.6,
    outputPricePerMTok: 2.5,
    tags: ["long_context", "balanced"],
    enabled: false,
    maskedKey: "未配置",
    status: "untested",
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    kind: "zhipu",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4.6",
    contextWindow: 128_000,
    inputPricePerMTok: 1,
    outputPricePerMTok: 5,
    tags: ["balanced"],
    enabled: false,
    maskedKey: "未配置",
    status: "untested",
  },
  {
    id: "ollama",
    name: "Ollama Local",
    kind: "ollama",
    baseUrl: "http://localhost:11434/v1",
    model: "qwen3-coder",
    contextWindow: 32_000,
    inputPricePerMTok: 0,
    outputPricePerMTok: 0,
    tags: ["privacy_first", "low_cost", "code_first"],
    enabled: false,
    maskedKey: "本地无需密钥",
    status: "untested",
  },
];

export const seedMemories: MemoryRecord[] = [
  {
    id: "mem-profile-1",
    kind: "profile",
    content: "用户偏好中文界面，任务开始前希望看到执行计划和 Token 预算。",
    source: "onboarding",
    confidence: 0.92,
    enabled: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    embeddingId: "local-profile-1",
  },
  {
    id: "mem-project-1",
    kind: "project",
    content: "AstraFlow 使用 Tauri + React + TypeScript，运行时由本地 Agent Runtime 协调。",
    source: "project-plan",
    confidence: 0.88,
    enabled: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    embeddingId: "local-project-1",
  },
  {
    id: "mem-episodic-1",
    kind: "episodic",
    content: "高风险命令必须先生成审批请求，用户批准前不能执行。",
    source: "security-policy",
    confidence: 0.95,
    enabled: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    embeddingId: "local-episodic-1",
  },
  {
    id: "mem-procedural-1",
    kind: "procedural",
    content: "代码类任务默认先读取项目结构，再生成 Coding Plan，最后运行验证命令。",
    source: "built-in-skill",
    confidence: 0.9,
    enabled: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    embeddingId: "local-procedural-1",
  },
];

export const builtInSkills: SkillManifest[] = [
  {
    name: "coding-plan",
    version: "0.1.0",
    description: "为代码任务生成影响面、修改策略、验证命令和回滚建议。",
    entry: "SKILL.md",
    permissions: [permissions["fs.read"], permissions["fs.write"]],
    scripts: {
      inspect: "node scripts/inspect-workspace.js",
    },
    enabled: true,
    installedAt: new Date().toISOString(),
  },
  {
    name: "weekly-report",
    version: "0.1.0",
    description: "读取任务日志和 Token 用量，生成结构化周报。",
    entry: "SKILL.md",
    permissions: [permissions["fs.read"]],
    enabled: false,
    installedAt: new Date().toISOString(),
  },
];

export const builtInMcpServers: McpServerManifest[] = [
  {
    name: "filesystem-safe",
    transport: "stdio",
    command: "npx @modelcontextprotocol/server-filesystem",
    permissions: [permissions["fs.read"], permissions["fs.write"]],
    enabled: true,
    health: "healthy",
    installedAt: new Date().toISOString(),
  },
  {
    name: "browser-automation",
    transport: "http",
    url: "http://127.0.0.1:7331/mcp",
    permissions: [permissions["network.http"]],
    enabled: false,
    health: "offline",
    installedAt: new Date().toISOString(),
  },
];
